

services:
  langtranslator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4


  # langtranslator-demo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.streamlit
  #   ports:
  #     - "8501:8501"
  #   env_file:
  #     - .env
  #   restart: unless-stopped

volumes:
  data:
