# glossary.py
# Professional glossary storage for English-to-Dutch medical/clinical terms

dutch = {
    # Product and Treatment Terms
    'CAMZYOS®': 'CAMZYOS®',
    'Mavacamten': 'Mavacamten',
    'First-in-class cardiac myosin inhibitor': 'Eerste-in-zijn-klasse cardiale myosineremmer',
    'Cardiac Myosin Inhibitor': 'Cardiale myosineremmer',
    'Targeted mechanism of action': 'Gericht werkingsmechanisme',
    'Mechanism of Action': 'Werkingsmechanisme',
    # Medical/Clinical Conditions
    'HCM – Hypertrophic Cardiomyopathy': 'HCM – Hypertrofische Cardiomyopathie',
    'Symptomatic obstructive hypertrophic cardiomyopathy': 'Symptomatische obstructieve hypertrofische cardiomyopathie',
    'Obstructive Hypertrophic Cardiomyopathy (oHCM)': 'obstructieve hypertrofische cardiomyopathie (HOCM)',
    'Cardiac conditions': 'Hartaandoeningen',
    'Atrial Fibrillation (AFib)': 'Atriumfibrilleren',
    'Heart': 'Hart',
    'Heart Failure': 'Hartfalen',
    'Stroke': 'Beroerte',
    'Dizziness': 'Duizeligheid',
    'Dyspnea': 'Dyspneu',
    'Syncope': 'Syncope',
    # Clinical Trial References
    'EXPLORER-HCM': 'EXPLORER-HCM',
    'VALOR-HCM': 'VALOR-HCM',
    'Clinical trial': 'Klinische studie',
    'Phase 3 Trials': 'Fase 3-studies',
    'Treatment duration – 30 weeks': 'Behandelduur – 30 weken',
    'Patient-reported outcomes': 'Patiëntgerapporteerde uitkomsten',
    'Primary and secondary endpoints': 'Primaire en secundaire eindpunten',
    'Inclusion Criteria': 'Inclusiecriteria',
    'Exclusion Criteria': 'Exclusiecriteria',
    # Clinical Benefits / Efficacy Terms
    'Efficacy': 'Doeltreffendheid',
    'Clinical benefits': 'Klinische voordelen',
    'Symptom management': 'Symptoombeheer',
    'Symptom Control / Symptom Relief': 'Symptoomcontrole',
    'Quality of life': 'Levenskwaliteit',
    'Functional capacity': 'Functionele capaciteit',
    'Functional status': 'Functionele status',
    'Exercise Capacity': 'Inspanningscapaciteit',
    'Therapeutic outcomes': 'Therapeutische uitkomsten',
    'Improvement scores': 'Verbeteringsscores',
    'Enhanced therapeutic outcomes': 'Verbeterde therapeutische uitkomsten',
    'Sustained relief from symptoms': 'Aanhoudende verlichting van symptomen',
    'Rapid decline in LVOT gradients': 'Snelle afname van LVUT-gradiënten',
    'Valsalva LVOT Gradient': 'Valsalva LVOT-gradiënt',
    'Effective management': 'Effectief beheer',
    'Unmet Need': 'Onvervulde behoefte',
    'Unmet Medical Need': 'Unmet medical need',
    'Burden of Disease': 'Ziektelast',
    # Cardiac Function Metrics
    'LVOT – Left Ventricular Outflow Tract': 'LVUT – Linkerventrikel-uitstroomtractus',
    'Left Ventricular Outflow Tract Obstruction': 'Linker ventrikel uitstroombaan obstructie',
    'Left Ventricular Ejection Fraction (LVEF)': 'Linkerventrikelejectiefractie (LVEF)',
    'Left ventricle (LV)': 'Linker ventrikel (LV)',
    'Left ventricular systolic function': 'Systolische functie van de linkerventrikel',
    'Mean global left ventricular systolic function': 'Gemiddelde globale systolische functie van de linkerventrikel',
    'Left ventricular obstruction': 'Obstructie van de linkerventrikel',
    'Systolic Dysfunction': 'Systolische disfunctie',
    'Impaired Relaxation': 'Verminderde ontspanning',
    'Hypercontractility': 'Hypercontractiliteit',
    'Myosin-actin Cross-bridges': 'Myosine-actine kruisbruggen',
    # Safety and Tolerability Terms
    'Safety profile': 'Veiligheidsprofiel',
    'Comparable to placebo': 'Vergelijkbaar met placebo',
    'Favorable safety profile': 'Gunstig veiligheidsprofiel',
    'No unexpected safety concerns': 'Geen onverwachte veiligheidsproblemen',
    'Adverse Reactions (AEs)': 'Bijwerkingen',
    'Adverse events': 'Bijwerkingen',
    'Serious adverse events': 'Ernstige bijwerkingen',
    'Tolerability': 'Verdraagbaarheid',
    'Modest reductions in LVEF': 'Bescheiden dalingen in LVEF',
    'No discontinuation due to LVEF': 'Geen behandelingsstop vanwege LVEF',
    'Contraindications': 'Contra-indicaties',
    'Embryo-foetal Toxicity': 'Embryofoetale toxiciteit',
    'Women of Childbearing Potential': 'Vrouwen in de vruchtbare leeftijd',
    # Comparators and Controls
    'Placebo': 'Placebo',
    'Mavacamten vs. Placebo group': 'Mavacamten versus placebogroep',
    'Superiority over placebo': 'Superieur ten opzichte van placebo',
    # Medications and Dosing
    'Beta-blockers (BBs)': 'Bètablokkers (BBs)',
    'Diltiazem': 'Diltiazem',
    'Verapamil': 'Verapamil',
    'Dosing / Posology': 'Dosering',
    'Concomitant Use': 'Gelijktijdig gebruik',
    'Maintenance Phase': 'Onderhoudsfase',
    # Genetic and Biomarker Terms
    'CYP2C19 (Cytochrome P450 2C19)': 'CYP2C19 (Cytochroom P450 2C19)',
    'CYP2C19 Poor Metabolizer Phenotype': 'Trage CYP2C19 metaboliseerder',
    'Genotyping': 'Genotypering',
    'Sarcomere Mutations': 'Sarcomeermutaties',
    'Biomarkers': 'Biomarkers',
    'NT-proBNP': 'NT-proBNP',
    # Assessment Tools and Scores
    'HCMSQ SoB': 'HCMSQ SoB',
    'KCCQ-23 CSS': 'KCCQ-23 CSS',
    'NYHA Class': 'NYHA-klasse',
    'pVO2': 'pVO2',
    # Guidelines and Therapy
    'ESC Guidelines (European Society of Cardiology Guidelines)': 'ESC-richtlijnen',
    'Septal Reduction Therapy (SRT)': 'Septal Reduction Therapy (SRT)',
    'Indication': 'Indicatie',
    'Progression to Severe HF Symptoms': 'Progressie naar ernstige HF-symptomen',
    # Healthcare System Terms
    'Multidisciplinary Centre / Expert Centres': 'Behandelcentra',
    'Reimbursement': 'Vergoeding',
    # Communication Terms
    'Subject line': 'Onderwerpregel',
    'Preheader': 'Preheader',
    'Click here for the VPI': 'Klik hier voor de VPI',
    'Feel free to reach out': 'Neem gerust contact op',
}